timeout: 3
    
# Graphics mode and Splash screen
term_palette: ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff;ffffff
term_background: #00000000
# Hide terminal by placing it out of view or making it very small initially if possible, 
# but Limine's wallapper will be the main background.
wallpaper: boot():/splash.jpg

/BoredOS
    protocol: limine

    kernel_path: boot():/boredos.elf
